services:
  # PostgreSQL Datenbank
  postgres:
    image: postgres:15-alpine
    container_name: transcendence_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: transcendence_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcendence -d transcendence_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Backend
  backend:
    build: ./backend
    container_name: transcendence_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: transcendence
      DB_PASSWORD: secretpassword
      DB_NAME: transcendence_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production-12345
    depends_on:
      postgres:
        condition: service_healthy
  
  # Frontend
  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  # Adminer (korrigiert)
  adminer:
    image: adminer:latest
    container_name: transcendence_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: