version: '3'
services:
  backend:
    build: ./backend
    container_name: transcendence_backend
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=test_12
    command: npm run start
  
  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend