version: '3.8'
services:
  # Neue PostgreSQL Datenbank
  postgres:
    image: postgres:15-alpine
    container_name: transcendence_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: transcendence_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Backend anpassen
  backend:
    build: ./backend
    container_name: transcendence_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: transcendence
      DB_PASSWORD: secretpassword
      DB_NAME: transcendence_db
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "3000:80"
  
  # Adminer funktioniert jetzt problemlos!
  adminer:
    image: adminer:latest
    container_name: transcendence_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: