version: '3.8'

services:
  # PostgreSQL Datenbank
  postgres:
    image: postgres:15-alpine
    container_name: transcendence_db
    restart: always
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: transcendence_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcendence"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transcendence_network

  # Backend Service
  backend:
    build: ./backend
    container_name: transcendence_backend
    restart: always
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: transcendence
      DB_PASSWORD: secretpassword
      DB_NAME: transcendence_db
      JWT_SECRET: your_jwt_secret_here_change_in_production
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence_network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    restart: always
    environment:
      REACT_APP_API_URL: https://ft_transcendence/api
    networks:
      - transcendence_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: transcendence_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/etc/nginx/html:ro
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - transcendence_network

  # Adminer für Database Management
  adminer:
    image: adminer:latest
    container_name: transcendence_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence_network

volumes:
  postgres_data:

networks:
  transcendence_network:
    driver: bridge